[data]
    clean_repo = true

[sourceVCS]
    autoCommit = false
    autoPush = false

[diff]
    exclude = ["scripts"]
    
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]