require("plugins/setup")

require("utils")
require("keymaps")
require("settings")
require("autocmds")
require("icons")

-- require("plugins.codeium")
require("plugins.supermaven")
require("plugins.colorscheme")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.compe")
require("plugins.blink")
require("plugins.lsp")
require("plugins.null_ls")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.comment")
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.hop")
require("plugins.nvim-tree")
-- require("plugins.oil")
require("plugins.impatient")
require("plugins.toggleterm")
require("plugins.avante")
require("plugins.transparent")
require("plugins.c2p")
require("plugins.dependency-tree")
-- require("plugins.autopair")
-- require("plugins.indentblank")
-- require("plugins.lspsaga")
